<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Pluto Zhang" />

<meta name="date" content="2022-12-14" />

<title>Final Project BST 260</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="finalproj.html">BST260FinalProj</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Final Project BST 260</h1>
<h4 class="author">Pluto Zhang</h4>
<h4 class="date">2022-12-14</h4>

</div>


<div id="introduction" class="section level1">
<h1><strong>Introduction</strong></h1>
<p>Happiness level of a country is very important to the development of
the country, and influences the all social sectors such as health,
economy, social stability, so on and so forth. To figure out how the
general social wellness of a country influences its overall happiness
level, and how happy a country is with respect to its neighbors, is
important.</p>
<p>My central questions are: 1. How does the happiness level of a
country relate to its social wellness factors? Would the social wellness
of a country predict its happiness level? 2. Do countries that locate
geographically close to each other also have similarity in terms of
happiness levels?</p>
<p>My goal is to figure out how well can social factors, including GDP,
social support, generosity and freedom, could forecast the happiness
levels of a country in the world. In addition, we want to have a gist of
how happy the global regions are, and whether the regions that are
geographically close are closer in terms of social factor scores and
happiness levels.</p>
<p>This project aims to 1. Generate a linear regression model to predict
the level of happiness across countries in the world, using social
factors associated with happiness; 2. Assess whether the regions with
similar happiness levels and social characters are geographically close,
across 2020 to 2021. Use hierarchical clustering to figure out if the
clusters of regions belong to the same continent or are different in
2020 and 2021.</p>
<p><em>1. Datasets:</em></p>
<p>This project mainly uses two datasets: the 2020 and 2021 World
Happiness Report datasets, both datasets are pulled from the World
Happiness Report website, which provides numerical data related to the
country’s level of happiness for countries over the world. The variables
included in the datasets are: the adjusted happiness scores, log of the
GDP per capita, the social support, healthy life expectancy at birth,
freedom to make life choices, generosity and perception of corruption.
All the variables are weighted numerical values, and the higher the
value is, the more this country achieves in the corresponding variable.
There is one unique variable: perception towards corruption, whose score
indicates how severe the corruption within the government is, as
perceived by the public.</p>
<p>The 2020 dataset has data for 153 countries, while the 2021 dataset
has data for 149 countries. since the number of countries are different
in happy 20 and happy 21, for now, because the number of country
difference is less than 5%, I removed the countries that differ from
each other from the dataset, so each dataset now has 148 countries.</p>
<p>There is no NA values in the 2021 world happiness dataset, which is
desirable and indicates that there is no missing data.</p>
<pre><code>## # A tibble: 10 × 2
##    Region                             happyavg
##    &lt;chr&gt;                                 &lt;dbl&gt;
##  1 South Asia                             4.44
##  2 Sub-Saharan Africa                     4.49
##  3 Middle East and North Africa           5.22
##  4 Southeast Asia                         5.41
##  5 Commonwealth of Independent States     5.47
##  6 East Asia                              5.81
##  7 Latin America and Caribbean            5.91
##  8 Central and Eastern Europe             5.98
##  9 Western Europe                         6.91
## 10 North America and ANZ                  7.13</code></pre>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>From the summary histogram, the happiness scores are approximately
normally distributed, with most of the countries’ happiness scores at
around 5 and 6, a few below 3 and above 7. This finding indicates that
most of the countries have moderate happiness scores among the 148
countries.</p>
<p>The region with the highest happiness score are North America and
Western Europe.</p>
<pre><code>## # A tibble: 10 × 2
##    Region                             happyavg
##    &lt;chr&gt;                                 &lt;dbl&gt;
##  1 Sub-Saharan Africa                     4.38
##  2 South Asia                             4.48
##  3 Middle East and North Africa           5.23
##  4 Commonwealth of Independent States     5.36
##  5 Southeast Asia                         5.38
##  6 East Asia                              5.71
##  7 Central and Eastern Europe             5.88
##  8 Latin America and Caribbean            5.98
##  9 Western Europe                         6.90
## 10 North America and ANZ                  7.17</code></pre>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>From the summary histogram, the 2020 happiness scores are
approximately normally distributed, with most of the countries’
happiness scores at around 4 to 6, a few below 3 and above 7. This
finding indicates that most of the countries have moderate happiness
scores among the 153 countries. Compared to 2021 happiness score data,
the countries in 2020 have in general lower happiness score, with more
countries hitting the values lower than 4 and less countries higher than
7.</p>
<p>The regions with the highest happiness score are North America and
Western Europe, in both 2020 and 2021.</p>
<ol start="2" style="list-style-type: decimal">
<li><em>Analysis Methods</em></li>
</ol>
<p>Two major analysis methods will be used in this project to address
the two central questions:</p>
<ol style="list-style-type: decimal">
<li><p>Linear Regression Model Fitting For the first question, we want
to create a model that predicts the happiness score based on other
social factors. For this part, I select the linear regression model to
achieve the prediction, because it’s a long proven and simple
statistical method to assess the relationship between variables. First,
I examined the correlation between the social factors with happiness, to
see which social factors are the most relevant in foreseeing the
happiness level of countries. Then I fit the model linearly, that the
2020 data will be used as the training set, while the 2021 data will be
used as the test set of the model to evaluate the fit. I compared two
different models by including in different covariates, and comapred
their values of goodness of fit.</p></li>
<li><p>Hierarchical and K-means Clustering For the second question, I
first want to see whether there exists any clusters of regions based on
the happiness scores and social factors. I then plot these clusters on
the world map, to see whether these clusters of regions geographically
locate close to each other, or the regions that belong to the same
cluster locate far apart. The hierarchical clustering method is used,
because it’s useful in dividing the regions into groups, so that it’s
easy to visualize on the world map how closely located these clusters of
regions are.</p></li>
</ol>
</div>
<div id="results" class="section level1">
<h1><strong>Results</strong></h1>
<p><em>Part1 Linear Regression Model</em></p>
<p>First, let’s examine the strength of correlation of the factors with
happiness is examined using pearson correlation matrices.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>From the correlation matrices we can see that GDP, social support,
healthy life expectation are the factors that most strongly correlates
with the happiness levels of the countries, and all three indicates a
strong positive correlation with happiness. Freedom indicates a moderate
positive correlation with happiness score,<br />
while the level of corruption indicates a moderate negative correlation
with happiness score. The level of generosity did not present a strong
correlation with happiness score.</p>
<p>Thus, for the final model, I chose LogGDP+Support+HLE+Freedom+Corrupt
as the predictors for happiness score.</p>
<pre><code>## [1] &quot;This is the RMSE value of the first model: 0.535&quot;</code></pre>
<pre><code>## [1] &quot;This is the R square value of the first model: 0.752&quot;</code></pre>
<p>The RMSE value at 0.535 and the R square of 0.752 indicates that the
model is in general good at predicting the happiness score for 2021
happiness score.</p>
<p>Now we see the correlation of the predicted data versus the real 2021
happiness score:</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>From the graph we can see that the prediction is generally accurate,
with high correlation between the predicted values and the real
happiness scores.</p>
<p>We can compare this model with another model that includes only the
three most important variables, GDP, social support, healthy life
expectation as the covariates.</p>
<pre><code>## [1] &quot;This is the RMSE value of the reduced model: 0.595&quot;</code></pre>
<pre><code>## [1] &quot;This is the R squared value of the reduced model: 0.693&quot;</code></pre>
<p>This new model results in RMSE of 0.595, which is bigger than the
RMSE of the full model at 0.535, indicating that this model is not as
good as the full model in terms of fitting. It also has adjusted R
squared value of 0.693, which is smaller than the adjusted R squared
value of the full model at 0.752, which further supports the point that
this model is worse in fitting as compared to the full model.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Looking at the predicted versus real happiness score value graph we
can see that there are more scatters compared to the model with more
covariates. Thus, the model that includes freedom and perception of
corruption as covariates is better in predicting the happiness scores,
and all the 5 covariates, LogGDP, Support, HLE, Freedom and Corrupt are
positively correlated with happiness score, leading to a strong positive
correlation.</p>
<p><em>Part 2 Clustering Analysis</em></p>
<p>First, generate dataframes of the average of by regions.</p>
<p><em>Part 2-1 Hierarchical clustering</em></p>
<p>Next, generate clusters of the regions based on the distance of each
of the social factors:</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>From the 2020 dendrogram, there are 4 main clusters as divided by the
blue line:</p>
<p>The first cluster: East Asia, Western Europe, North America and ANZ
(Australia and New Zealand)</p>
<p>The second cluster: South Asia, Middle East and North Africa,
Commonwealth and Independent States, Southeast Asia.</p>
<p>The third cluster: Central and Eastern Europe, Latin America and
Caribbean.</p>
<p>The second and the third cluster are closer to each other in terms of
the social factors and happiness scores.</p>
<p>The forth cluster, which is also the cluster farthest away from the
other three clusters, is Sub-saharan Africa.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>When plotting the 2020 dendrogram on the world map, it shows
consistent colorings for continents such as the African and American
continent, and the colorings usually spans may neighboring countries.
It’s interesting how eastern European and south American countries
belong to the same cluster, despite the geographical distance.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>From the 2021 dendrogram, there are 4 main clusters as divided by the
line:</p>
<p>The first cluster: East Asia, Western Europe, North America and ANZ
(Australia and New Zealand)</p>
<p>The second cluster: South Asia, Middle East and North Africa,
Commonwealth and Independent States, Southeast Asia.</p>
<p>The third cluster: Central and Eastern Europe, Latin America and
Caribbean.</p>
<p>The forth cluster, is Sub-Saharan Africa.</p>
<p>For 2021 data, the first and third clusters are closer to each other,
while the second and the forth clusters are closer to each other.</p>
<p>It’s worth noticing that the regions within each cluster didn’t
change from 2020 to 2021.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>From the plots above, we can see that: Under hierarchical
clustering:</p>
<ol style="list-style-type: decimal">
<li><p>The clusters of regions with similarity in happiness score and
social factor data did not change much from 2020 to 2021, as shown on
the map.</p></li>
<li><p>The regions that belong to the same cluster, or have similar
happiness level, do not necessarily locate close to each other or on the
same continent. For countries on the American continent, it’s clear that
the North American countries are similar in happiness and socio-economic
levels as a cluster, while south American countries form a cluster as
well. Among Asian countries, however, the happiness levels vary a lot
from subregions, such that the South Asian and Southeast Asian have very
different happiness scores as compared to east Asian countries. However,
each cluster tends to have some degree of spread and spanning across the
same continent, including at least multiple neighboring countries at a
time.</p></li>
</ol>
<p>Now let’s compare the results of hierarchical clustering to k-means
clustering:</p>
<p><em>Part 2-2 K-means clustering</em></p>
<pre><code>##                 Sub-Saharan Africa                         South Asia 
##                                  2                                  4 
##       Middle East and North Africa Commonwealth of Independent States 
##                                  4                                  4 
##                     Southeast Asia                          East Asia 
##                                  4                                  1 
##         Central and Eastern Europe        Latin America and Caribbean 
##                                  3                                  3 
##                     Western Europe              North America and ANZ 
##                                  1                                  1</code></pre>
<p>For k-means clustering with 4 clusters, we can see that: for 2020
data,</p>
<p>The first cluster:</p>
<p>South Asia, Middle East and North Africa, Commonwealth and
Independent States, Southeast Asia.</p>
<p>The second cluster, is Sub-Saharan Africa.</p>
<p>The third cluster: East Asia, Western Europe, North America and ANZ
(Australia and New Zealand)</p>
<p>The fourth cluster: Central and Eastern Europe, Latin America and
Caribbean.</p>
<p>The division of regions by clusters is the same as using hierarchical
clustering.</p>
<p>Now visualize that on the world map:</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<p>As can see from the world map, for year 2020, the 4 clusters divided
by the k-means approach are the same as the 4 clusters generated by the
hierarchical approach.</p>
<p>Now let’s look at the 2021 data:</p>
<pre><code>##                         South Asia                 Sub-Saharan Africa 
##                                  1                                  4 
##       Middle East and North Africa                     Southeast Asia 
##                                  1                                  1 
## Commonwealth of Independent States                          East Asia 
##                                  1                                  2 
##        Latin America and Caribbean         Central and Eastern Europe 
##                                  3                                  3 
##                     Western Europe              North America and ANZ 
##                                  2                                  2</code></pre>
<p>For k-means clustering with 4 clusters, we can see that: for 2021
data,</p>
<p>The first cluster: Sub-Saharan Africa</p>
<p>The second cluster, South Asia</p>
<p>the third cluster: Middle East and North Africa, Commonwealth and
Independent States, Southeast Asia, Central and Eastern Europe, Latin
America and Caribbean.</p>
<p>The fourth cluster: East Asia, Western Europe, North America and ANZ
(Australia and New Zealand)</p>
<p>This time, the clusters have different contents as compared to the
hierarchical approach on 2021 data, that South Asia itself consists a
single cluster, while Middle East and North Africa, Commonwealth and
Independent States, Southeast Asia are put into the same cluster with
Central and Eastern Europe, Latin America and Caribbean.</p>
<p><img src="fpEDA_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre><code>## # A tibble: 10 × 8
##    Region                 Happy…¹ GDPavg Suppo…² HLEavg Freed…³ Genero…⁴ Corru…⁵
##    &lt;chr&gt;                    &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;    &lt;dbl&gt;   &lt;dbl&gt;
##  1 South Asia                4.44   8.68   0.703   62.7   0.765  0.0427    0.797
##  2 Sub-Saharan Africa        4.49   8.08   0.697   55.9   0.723  0.0134    0.766
##  3 Middle East and North…    5.22   9.67   0.798   65.6   0.716 -0.0798    0.762
##  4 Southeast Asia            5.41   9.42   0.820   64.9   0.909  0.156     0.709
##  5 Commonwealth of Indep…    5.47   9.40   0.872   65.0   0.817 -0.036     0.725
##  6 East Asia                 5.81  10.4    0.860   71.3   0.764 -0.0623    0.683
##  7 Latin America and Car…    5.91   9.37   0.840   67.1   0.832 -0.0677    0.793
##  8 Central and Eastern E…    6.04  10.1    0.893   68.5   0.800 -0.0863    0.847
##  9 Western Europe            6.91  10.8    0.914   73.0   0.859 -0.00319   0.523
## 10 North America and ANZ     7.13  10.8    0.934   72.3   0.899  0.12      0.449
## # … with abbreviated variable names ¹​Happyavg, ²​Supportavg, ³​Freedomavg,
## #   ⁴​Generosityavg, ⁵​Corruptavg</code></pre>
<p>By looking at the social factors data of 2021, the first and second
clusters, Sub-Saharan Africa and South Asia, have the lowest happiness
score values, with relatively low GDP, Health life expectancy and Social
Support, but relatively high or average in other wellness indicators.
This explains why South Asia is separated from the cluster with other
regions for the k-means clustering approach, because k-means clustering
is better in ruling out clusters with different sizes as compared to
hierarchical clustering. so despite South Asia is similar in other
regions in terms of generosity and corrup scores, it is still singled
out as a cluster with low happiness score, using k-means approach.</p>
</div>
<div id="conclusion" class="section level1">
<h1><strong>Conclusion</strong></h1>
<p>Our two research questions are,</p>
<ol style="list-style-type: decimal">
<li><p>How does the happiness level of a country relate to its social
wellness factors? Would the social wellness of a country predict its
happiness level?</p></li>
<li><p>Do regions that locate geographically close to each other also
have similarity in terms of happiness levels?</p></li>
</ol>
<p>To answer the first question, I used linear regression model fitting,
using the 2020 data as the training set and the 2021 data as the test
set, and it turns out that the linear regression model that includes the
5 covariates, LogGDP, Support, HLE, Freedom and Corrupt is an optimal
model that can predict the happiness with relatively high accuracy, with
a small RMSE value. And all 5 covariates are positively and strongly
correlated with happiness score.</p>
<p>For the second question, I used hierarchical clustering and k-means
clustering to figure out whether the global regions that locate
geographically close to each other are also close in happiness level,
using the average scores of social wellness factors by region in 2020
and 2021 as inputs, generating the clusters and then visualize the
countries that belong to the same cluster by giving them same color on
the world map.</p>
<p>Under hierarchical clustering, I found out that the clusters of
regions similar in happiness level did not change much from 2020 to
2021, and that the regions that belong to the same cluster, or have
similar happiness level, do not necessarily locate close to each other
or on the same continent, but, each cluster tends to spread across the
at least multiple neighboring countries at the same continent. The
k-means clustering results for 2020 is the same as the hierarchical
clustering results, but for 2021 data, South Asia is ruled out as a
single cluster, because its happiness score is the lowest in 2021,
despite its similarity with other regions in some other social factors
like generosity and perception of corruption, and this difference is
caught by the k-means clustering approach. But in general, the division
of global regions in terms of happiness level does not change much from
2020 to 2021, and that neighboring countries in African, North and South
American tend to have similarities in social wellness, while in Asia,
the differences in social wellness factors could be larger between
different parts of Asian continent.</p>
<p>My approaches generally answered the two questions very well, because
1. the resulting regression model generates a good fit for the data and
the prediction achieves relatively high accuracy. 2. For the clustering
analysis, the outcomes are relatively consistent and coherent across
differnet years and clustering approaches, and by plotting the
clustering results on the world map, my approach is easy to visualize
and interpret.</p>
<p>If I have more time, I would include in more datasets, such as the
2018 and 2019 datasets as well, to see whether the occurrences of
COVID-19 has effects on the world happiness levels across countries. I
would also consider adding in COVID infection data by country, to see
whether that could also be a covariate that helps predict the happiness
score by country.</p>
</div>
<div id="references" class="section level1">
<h1><strong>References</strong></h1>
<p>The sources of 2020 and 2021 World Happiness Score data:</p>
<ol style="list-style-type: decimal">
<li><p>Helliwell, John F., et al. “World Happiness Report 2020.” The
World Happiness Report, 20 Mar. 2020,
worldhappiness.report/ed/2020/.</p></li>
<li><p>Helliwell, John F., et al. “World Happiness Report 2021.” The
World Happiness Report, 20 Mar. 2021,
worldhappiness.report/ed/2021/.</p></li>
</ol>
</div>
<div id="appendix" class="section level1">
<h1><strong>Appendix</strong></h1>
<pre class="r"><code>knitr::opts_chunk$set(warning=FALSE, message = FALSE, echo=FALSE)
library(tidyverse)
library(dplyr)
library(dslabs)
library(caret)
library(ggplot2)
library(ggrepel)
library(plm)


#explore the world happiness score dataset
happy21 &lt;- read_csv(&#39;world-happiness-report-2021.csv&#39;)

#colnames(happy21)
#From the summary statistics: we can see that there is no NA values in the 2021 world happiness dataset, which is desirable and indicates that there is no missing data. 

summary(happy21)

#select the wanted columns and rename them in 2021 dataset
happy21 &lt;- happy21 |&gt; select(&#39;Country name&#39;,&#39;Regional indicator&#39;,&#39;Ladder score&#39;,&#39;Logged GDP per capita&#39;, &#39;Social support&#39;,  &#39;Healthy life expectancy&#39;, &#39;Freedom to make life choices&#39;,   &#39;Generosity&#39;,&#39;Perceptions of corruption&#39; )
colnames(happy21) &lt;- c(&#39;Country&#39;, &#39;Region&#39;,&#39;Happy&#39;, &#39;LogGDP&#39;,&#39;Support&#39;,&#39;HLE&#39;,&#39;Freedom&#39;,&#39;Generosity&#39;, &#39;Corrupt&#39;)
#HLE stands for health life expectancy
#make sure that the countries in this dataset are unique from each other
length(unique(happy21$Country)) == nrow(happy21)

#EDA
# first make a histogram of average score of happiness by country and by region

eda21 &lt;- happy21 |&gt; group_by(Region) |&gt; summarize(happyavg = mean(Happy)) |&gt; arrange(happyavg)

print(eda21)
happy21 |&gt; ggplot() + geom_histogram(aes(x=Happy), bins=40)
#Now preprocess the 2020 happiness data:
#2020 happiness data
happy20 &lt;- read_csv(&#39;WHR20_DataForFigure2.1.csv&#39;)

happy20 &lt;- happy20 |&gt; select(&#39;Country name&#39;,&#39;Regional indicator&#39;,&#39;Ladder score&#39;, &#39;Logged GDP per capita&#39;, &#39;Social support&#39;,  &#39;Healthy life expectancy&#39;, &#39;Freedom to make life choices&#39;,   &#39;Generosity&#39;,&#39;Perceptions of corruption&#39; )
colnames(happy20) &lt;- c(&#39;Country&#39;, &#39;Region&#39;,&#39;Happy&#39;, &#39;LogGDP&#39;,&#39;Support&#39;,&#39;HLE&#39;,&#39;Freedom&#39;,&#39;Generosity&#39;, &#39;Corrupt&#39;)
#EDA
# first make a histogram of average have a general view of happiness by country and by region

region20&lt;- happy20 |&gt; group_by(Region) |&gt; summarize(happyavg = mean(Happy)) |&gt; arrange(happyavg)

print(region20)
happy20 |&gt; ggplot() + geom_histogram(aes(x=Happy), bins=40)

#nrow(happy20)
#nrow(happy21)
#since the number of countries are different in happy 20 and happy 21, for now, because the number of country difference is less than 5%, let&#39;s remove the countries that differ from each other. 

happy20 &lt;- happy20 |&gt; filter((Country %in% happy21$Country))
happy21 &lt;- happy21 |&gt; filter((Country %in% happy20$Country))
library(GGally)
happy20numeric &lt;- happy20 |&gt; select(-c(&#39;Country&#39;, &quot;Region&quot;))
happy21numeric &lt;- happy21 |&gt; select(-c(&#39;Country&#39;, &quot;Region&quot;))

ggcorr(happy20, 
       method = c(&quot;everything&quot;, &quot;pearson&quot;), 
       size = 5, hjust = 0.77,
       low = &#39;cornflowerblue&#39;, mid = &#39;white&#39;, high = &quot;lemonchiffon&quot;,
       label = TRUE, label_size = 4,
       layout.exp = 1) +
labs(title = &#39;Correlation Matrix&#39;,
    subtitle = &#39;Happiness correlation to social factors&#39;) 
ggcorr(happy21, 
       method = c(&quot;everything&quot;, &quot;pearson&quot;), 
       size = 5, hjust = 0.77,
       low = &#39;cornflowerblue&#39;, mid = &#39;white&#39;, high = &quot;lemonchiffon&quot;,
       label = TRUE, label_size = 4,
       layout.exp = 1) +
labs(title = &#39;Correlation Matrix&#39;,
    subtitle = &#39;Happiness correlation to social factors&#39;) 

library(caret)
# use the 2020 happiness data as the training set and the 2021 data as the test set.
#take a look at the summary of the model fit
fit1 &lt;- lm( Happy ~ LogGDP+Support+HLE+Freedom+Corrupt, data = happy20)
#summary(fit1)
y_hat1 &lt;- predict(fit1, newdata = happy21)

#see the RMSE
rmse1 &lt;- sqrt(mean((y_hat1-happy21$Happy)^2))
paste0(&#39;This is the RMSE value of the first model: &#39;,round(rmse1, 3))
#R-square
r1&lt;- R2(y_hat1, happy21$Happy)
paste0(&#39;This is the R square value of the first model: &#39;,round(r1, 3))

modeldata&lt;- happy21
modeldata$predicted &lt;- y_hat1
modeldata |&gt; ggplot(aes(predicted, Happy)) + geom_point() + geom_smooth()

fit2 &lt;- lm( Happy ~ LogGDP+Support+HLE, data = happy20)
#summary(fit2)
y_hat2 &lt;- predict(fit2, newdata = happy21)

rmse2 &lt;- sqrt(mean((y_hat2-happy21$Happy)^2))
paste0(&#39;This is the RMSE value of the reduced model: &#39;,round(rmse2, 3))
r2 &lt;- R2(y_hat2, happy21$Happy)
paste0(&#39;This is the R squared value of the reduced model: &#39;,round(r2, 3))
modeldata2&lt;- happy21
modeldata2$predicted &lt;- y_hat2
modeldata2 |&gt; ggplot(aes(predicted, Happy)) + geom_point() + geom_smooth()
region20all &lt;- happy20 |&gt; group_by(Region) |&gt; 
  summarize(Happyavg = mean(Happy),
            GDPavg = mean(LogGDP),
            Supportavg=mean(Support),
            HLEavg = mean(HLE),
            Freedomavg = mean(Freedom),
            Generosityavg = mean(Generosity), 
            Corruptavg = mean(Corrupt)) |&gt; 
  arrange(Happyavg)

region21all &lt;- happy21 |&gt; group_by(Region) |&gt; 
  summarize(Happyavg = mean(Happy),
            GDPavg = mean(LogGDP),
            Supportavg=mean(Support),
            HLEavg = mean(HLE),
            Freedomavg = mean(Freedom),
            Generosityavg = mean(Generosity), 
            Corruptavg = mean(Corrupt)) |&gt; 
  arrange(Happyavg)
region21alltibble &lt;- region21all
row20 &lt;- region20all$Region
region20all &lt;- region20all[,-1] |&gt; as.matrix()
rownames(region20all) &lt;- row20

row21 &lt;- region21all$Region
region21all &lt;- region21all[,-1] |&gt; as.matrix()
rownames(region21all) &lt;- row21


d20 &lt;- dist(region20all)
d21 &lt;- dist(region21all)

h20 &lt;- hclust(d20)
h21 &lt;- hclust(d21)
plot(h20, cex = 0.55, main = &quot;Clusters of regions by Happiness Level 2020&quot;, xlab = &quot;Region names&quot;)
abline(h=5, col=&quot;blue&quot;)

#Now get the vectors of countries that belong to each cluster:
cluster1_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;East Asia&#39;, &#39;Western Europe&#39;, &#39;North America and ANZ&#39;)) |&gt; select(&#39;Country&#39;)
cluster2_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;South Asia&#39;, &#39;Middle East and North Africa&#39;, &#39;Commonwealth and Independent States&#39;, &#39;Southeast Asia&#39;)) |&gt; select(&#39;Country&#39;)

cluster3_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;Central and Eastern Europe&#39;, &#39;Latin America and Caribbean&#39;)) |&gt; select(&#39;Country&#39;)
cluster4_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;Sub-Saharan Africa&#39;)) |&gt; select(&#39;Country&#39;)

#Plot the results on the world map

thismap = map_data(&quot;world&quot;)

cluster1_2020&lt;- cluster1_2020 |&gt; mutate(
  Country1 = case_when(Country ==&#39;Taiwan Province of China&#39; ~ &#39;Taiwan&#39;, 
                       Country == &#39;United States&#39;~ &#39;USA&#39;,
                       Country == &#39;United Kingdom&#39;~ &#39;UK&#39;,
                       TRUE ~ Country))

cluster3_2020 &lt;- cluster3_2020 |&gt; mutate(Country1 = Country)
cluster2_2020 &lt;- cluster2_2020 |&gt; mutate(Country1 = 
                                           case_when(
                                             Country ==&#39;Palestinian Territories&#39; ~ &#39;Palestine&#39;, 
                                             TRUE ~ Country))
cluster4_2020 &lt;- cluster4_2020 |&gt; mutate(Country1 = Country)

#set colors by the clusters of countries
thismap &lt;- mutate(thismap, fill =ifelse(region %in% cluster1_2020$Country1 ,&#39;darkseagreen&#39;,
                                        ifelse(region %in% cluster2_2020$Country1, &quot;deepskyblue&quot;,
                                        ifelse(region %in% cluster3_2020$Country1,&quot;dodgerblue&quot;,
                                        ifelse(region %in% cluster4_2020$Country1,&quot;lemonchiffon&quot;, 
                                        ifelse(str_detect(&#39;Congo&#39;, region),&#39;lemonchiffon&#39;,&#39;white&#39;))))))

# set the colors
ggplot(thismap, aes(long, lat, fill = fill, group=group)) + 
  geom_polygon(colour=&quot;gray&quot;) + ggtitle(&quot;Map of World&quot;) + 
  scale_fill_identity()
# the 2021 dendrogram: 
plot(h21, cex = 0.55, main = &quot;Clusters of regions by Happiness Level 2021&quot;, xlab = &quot;Region names&quot;)
abline(h=5, color = &#39;blue&#39;)

cluster1_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;East Asia&#39;, &#39;Western Europe&#39;, &#39;North America and ANZ&#39;)) |&gt; select(&#39;Country&#39;)
cluster2_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;South Asia&#39;, &#39;Middle East and North Africa&#39;, &#39;Commonwealth and Independent States&#39;, &#39;Southeast Asia&#39;)) |&gt; select(&#39;Country&#39;)

cluster3_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;Central and Eastern Europe&#39;, &#39;Latin America and Caribbean&#39;)) |&gt; select(&#39;Country&#39;)
cluster4_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;Sub-Saharan Africa&#39;)) |&gt; select(&#39;Country&#39;)



thismap = map_data(&quot;world&quot;)

cluster1_2021&lt;- cluster1_2021 |&gt; mutate(
  Country1 = case_when(Country ==&#39;Taiwan Province of China&#39; ~ &#39;Taiwan&#39;, 
                       Country == &#39;United States&#39;~ &#39;USA&#39;,
                       Country == &#39;United Kingdom&#39;~ &#39;UK&#39;,
                       TRUE ~ Country))

cluster3_2021 &lt;- cluster3_2021 |&gt; mutate(Country1 = Country)
cluster2_2021 &lt;- cluster2_2021 |&gt; mutate(Country1 = 
                                           case_when(
                                             Country ==&#39;Palestinian Territories&#39; ~ &#39;Palestine&#39;, 
                                             TRUE ~ Country))
cluster4_2021 &lt;- cluster4_2021 |&gt; mutate(Country1 = Country)

#set colors by the clusters of countries
thismap &lt;- mutate(thismap, fill =ifelse(region %in% cluster1_2021$Country1 ,&#39;darkseagreen&#39;,
                                        ifelse(region %in% cluster2_2021$Country1, &quot;deepskyblue&quot;,
                                        ifelse(region %in% cluster3_2021$Country1,&quot;dodgerblue&quot;,
                                        ifelse(region %in% cluster4_2021$Country1,&quot;lemonchiffon&quot;, 
                                        ifelse(str_detect(&#39;Congo&#39;, region),&#39;lemonchiffon&#39;,&#39;white&#39;))))))

# set the colors
ggplot(thismap, aes(long, lat, fill = fill, group=group)) + 
  geom_polygon(colour=&quot;gray&quot;) + ggtitle(&quot;Map of World&quot;) + 
  scale_fill_identity()
k20 &lt;- kmeans(region20all, centers = 4)
k20$cluster
cluster3_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;East Asia&#39;, &#39;Western Europe&#39;, &#39;North America and ANZ&#39;)) |&gt; select(&#39;Country&#39;)
cluster1_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;South Asia&#39;, &#39;Middle East and North Africa&#39;, &#39;Commonwealth and Independent States&#39;, &#39;Southeast Asia&#39;)) |&gt; select(&#39;Country&#39;)

cluster4_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;Central and Eastern Europe&#39;, &#39;Latin America and Caribbean&#39;)) |&gt; select(&#39;Country&#39;)
cluster2_2020 &lt;- happy20 |&gt; filter(Region %in% c(&#39;Sub-Saharan Africa&#39;)) |&gt; select(&#39;Country&#39;)
thismap = map_data(&quot;world&quot;)

cluster3_2020&lt;- cluster3_2020 |&gt; mutate(
  Country1 = case_when(Country ==&#39;Taiwan Province of China&#39; ~ &#39;Taiwan&#39;, 
                       Country == &#39;United States&#39;~ &#39;USA&#39;,
                       Country == &#39;United Kingdom&#39;~ &#39;UK&#39;,
                       TRUE ~ Country))


cluster1_2020 &lt;- cluster1_2020 |&gt; mutate(Country1 = 
                                           case_when(
                                             Country ==&#39;Palestinian Territories&#39; ~ &#39;Palestine&#39;, 
                                             TRUE ~ Country))
cluster2_2020 &lt;- cluster2_2020 |&gt; mutate(Country1 = Country)
cluster4_2020 &lt;- cluster4_2020 |&gt; mutate(Country1 = Country)

#set colors by the clusters of countries
thismap &lt;- mutate(thismap, fill =ifelse(region %in% cluster1_2020$Country1 ,&#39;lavender&#39;,
                                        ifelse(region %in% cluster2_2020$Country1, &quot;wheat&quot;,
                                        ifelse(region %in% cluster3_2020$Country1,&quot;darkslategrey&quot;,
                                        ifelse(region %in% cluster4_2020$Country1,&quot;honeydew&quot;, 
                                        ifelse(str_detect(&#39;Congo&#39;, region),&#39;wheat&#39;,&#39;white&#39;))))))

# set the colors
ggplot(thismap, aes(long, lat, fill = fill, group=group)) + 
  geom_polygon(colour=&quot;gray&quot;) + ggtitle(&quot;Map of World&quot;) + 
  scale_fill_identity()
k21 &lt;- kmeans(region21all, centers = 4)
k21$cluster

cluster4_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;East Asia&#39;, &#39;Western Europe&#39;, &#39;North America and ANZ&#39;)) |&gt; select(&#39;Country&#39;)
cluster2_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;South Asia&#39;)) |&gt; select(&#39;Country&#39;)

cluster3_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;Central and Eastern Europe&#39;, &#39;Latin America and Caribbean&#39;, &#39;Middle East and North Africa&#39;, &#39;Commonwealth and Independent States&#39;, &#39;Southeast Asia&#39;)) |&gt; select(&#39;Country&#39;)
cluster1_2021 &lt;- happy21 |&gt; filter(Region %in% c(&#39;Sub-Saharan Africa&#39;)) |&gt; select(&#39;Country&#39;)


thismap = map_data(&quot;world&quot;)

cluster4_2021 &lt;- cluster4_2021 |&gt; mutate(
  Country1 = case_when(Country ==&#39;Taiwan Province of China&#39; ~ &#39;Taiwan&#39;, 
                       Country == &#39;United States&#39;~ &#39;USA&#39;,
                       Country == &#39;United Kingdom&#39;~ &#39;UK&#39;,
                       TRUE ~ Country))


cluster3_2021 &lt;- cluster3_2021 |&gt; mutate(Country1 = 
                                           case_when(
                                             Country ==&#39;Palestinian Territories&#39; ~ &#39;Palestine&#39;, 
                                             TRUE ~ Country))
cluster2_2021 &lt;- cluster2_2021 |&gt; mutate(Country1 = Country)
cluster1_2021 &lt;- cluster1_2021 |&gt; mutate(Country1 = Country)

#set colors by the clusters of countries
thismap &lt;- mutate(thismap, fill =ifelse(region %in% cluster1_2021$Country1 ,&#39;rosybrown&#39;,
                                        ifelse(region %in% cluster2_2021$Country1, &quot;tan&quot;,
                                        ifelse(region %in% cluster3_2021$Country1,&quot;lightcyan4&quot;,
                                        ifelse(region %in% cluster4_2021$Country1,&quot;lightskyblue1&quot;, 
                                        ifelse(str_detect(&#39;Congo&#39;, region),&#39;rosybrown&#39;,&#39;white&#39;))))))

# set the colors
ggplot(thismap, aes(long, lat, fill = fill, group=group)) + 
  geom_polygon(colour=&quot;gray&quot;) + ggtitle(&quot;Map of World&quot;) + 
  scale_fill_identity()

print(region21alltibble)</code></pre>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
